### ISSUE TITLE
Test sidechain functionalities with Sphere by Horizen 2.0.0

### ISSUE THREAD

**Issue by Cermelli** [HorizenOfficial/Sphere_by_Horizen#37]
**HDE task**

Starting points:

- https://github.com/HorizenOfficial/Sidechains-SDK/blob/master/README.md
- https://github.com/HorizenOfficial/zend_oo/blob/sidechains_testnet/README.md

Required steps:
- Download Sphere by Horizen 2.0.0: https://github.com/HorizenOfficial/Sphere_by_Horizen_Sidechain_Testnet/releases/tag/desktop-v2.0.0-beta-sidechain-testnet
- Obtain free test ZEN (tZEN) via the Horizen Early Adopter Program (HEAP): https://heap.horizen.global/
- Use the dedicated commands on Sphere by Horizen to declare a new sidechain
- Perform a Forward Transfer from the mainchain to the sidechain
- Produce a detailed report that includes screenshots of the different steps
Please note: the report can be submitted in various ways. We're also in the process of adding file attachment support to our bounty claim form - there it will be possible to upload your report in .pdf, .docx or .md. For the time being, please submit the report by providing a link to a document or a Google Docs.
- Include any feedback you might have related to your test (recommendations, areas of improvements, …)

**For more info:** https://hde.horizen.global/tasks
***This bounty will be paid to the first 10 contributors submitting a report meeting our quality standards

**Comment by flbouchut** [comment]
Hi !

I wrote a report about this task, here's the link : https://cryptochu.fr/comment-lancer-une-sidechain-horizen-a-partir-du-wallet-sphere-by-horizen/
For now, it's a French report but I can translate it if necessary.

**Comment by angievi** [comment]
Hi @flbouchut thanks for the report, we will review it and come back to you. Thanks!

**Comment by luisantoniocrag** [comment]
Hey there! Is there still space available to submit my test?

**Comment by angievi** [comment]
yes @luisantoniocrag you can still submit your report! please let us know your ETC! Thanks!

**Comment by menuc** [comment]
I submitted the Chinese version, please check, thank you!
https://drive.google.com/file/d/12xfnQ5Cfwhe4-f6YX_q68VeFMxln50N0/view?ths=true

**Comment by downsun** [comment]
我提交了中文版本，请检查，谢谢！
https://drive.google.com/file/d/12xfnQ5Cfwhe4-f6YX_q68VeFMxln50N0/view?ths=true

**Comment by luisantoniocrag** [comment]
Hey @angievi  

Here is my report: https://github.com/luisantoniocrag/test-sidechain-functionalities-with-Sphere-by-Horizen-2.0.0

Sorry for the delay. I took the time to research what Horizen does with the side chains. This approach is great and I will be very aware of its development.

**Comment by angievi** [comment]
> https://drive.google.com/file/d/12xfnQ5Cfwhe4-f6YX_q68VeFMxln50N0/view?ths=true

Hi @downsun , could you please follow the steps here to claim your bounty? https://hde.horizen.io/landing-page/bounty-payout-policy , any questions please let me know! thanks :)

**Comment by angievi** [comment]
> Hey @angievi. There is my report: https://github.com/luisantoniocrag/test-sidechain-functionalities-with-Sphere-by-Horizen-2.0.0
> 
> Sorry for the delay. I took the time to research what Horizen does with the Sidechains. This approach is great and I will be very aware of its development.

Hi! @luisantoniocrag , Thank you for your contribution! We will review it and come back to you in the following days :) best regards!

**Comment by flbouchut** [comment]
Hi ! I translated my previous report in English and I added it and the French version to the PR #41 
I will try to go through the bounty claim process 😊

**Comment by angievi** [comment]
Hi! @flbouchut I'm reviewing your PR now, I'll come back with an answer soon, in the mean time can you follow the bounty claiming process please? https://hde.horizen.io/landing-page/bounty-payout-policy

**Comment by angievi** [comment]
> > Hey @angievi. There is my report: https://github.com/luisantoniocrag/test-sidechain-functionalities-with-Sphere-by-Horizen-2.0.0
> > Sorry for the delay. I took the time to research what Horizen does with the Sidechains. This approach is great and I will be very aware of its development.
> 
> Hi! @luisantoniocrag , Thank you for your contribution! We will review it and come back to you in the following days :) best regards!

Hey @luisantoniocrag can you follow our bounty claiming process please? https://hde.horizen.io/landing-page/bounty-payout-policy thank you!

**Comment by luisantoniocrag** [comment]
> > > Hey @angievi. There is my report: https://github.com/luisantoniocrag/test-sidechain-functionalities-with-Sphere-by-Horizen-2.0.0
> > > Sorry for the delay. I took the time to research what Horizen does with the Sidechains. This approach is great and I will be very aware of its development.
> > 
> > 
> > Hi! @luisantoniocrag , Thank you for your contribution! We will review it and come back to you in the following days :) best regards!
> 
> Hey @luisantoniocrag can you follow our bounty claiming process please? https://hde.horizen.io/landing-page/bounty-payout-policy thank you!

submitted! Thank you. =)

**Comment by angievi** [comment]
> Hi ! I translated my previous report in English and I added it and the French version to the PR #41
> I will try to go through the bounty claim process 😊

Hey @flbouchut could you please fill out the form so we can proceed with payment? here is the link: https://hde.horizen.io/landing-page/bounty-payout-policy 

if you have any questions please send me an email to: angie@horizen.io 

thank you!

**Comment by flbouchut** [comment]
> > Hi ! I translated my previous report in English and I added it and the French version to the PR #41
> > I will try to go through the bounty claim process 😊
> 
> Hey @flbouchut could you please fill out the form so we can proceed with payment? here is the link: https://hde.horizen.io/landing-page/bounty-payout-policy
> 
> if you have any questions please send me an email to: [angie@horizen.io](mailto:angie@horizen.io)
> 
> thank you!

Submitted ! Ty !

**Comment by bricou26** [comment]
Hi !

I wrote a guide about this task, here's the link : https://investisseurcrypto.com/wp-content/uploads/2020/12/Test-de-fonctionnalites-de-la-sidechain-avec-Sphere-de-Horizen-2.0.0.docx 

The guide is in French but I can translate it if necessary.

**Comment by angievi** [comment]
Hi @bricou26! Your submission is currently under review, I'll post here the following steps in case it complies with the requirements for the task.

Thank you for contributing to HDE!
Angie.

**Comment by angievi** [comment]
> Hi @bricou26! Your submission is currently under review, I'll post here the following steps in case it complies with the requirements for the task.
> 
> Thank you for contributing to HDE!
> Angie.

@bricou26 could you please follow the steps to fill the bounty form? : https://hde.horizen.io/landing-page/bounty-payout-policy 

Any questions, let me know!

Angie.

**Comment by bricou26** [comment]
> > Hi @bricou26! Your submission is currently under review, I'll post here the following steps in case it complies with the requirements for the task.
> > Thank you for contributing to HDE!
> > Angie.
> 
> @bricou26 could you please follow the steps to fill the bounty form? : https://hde.horizen.io/landing-page/bounty-payout-policy
> 
> Any questions, let me know!
> 
> Angie.

The process have been completed :) 


Do i need to close my pull request ?

Brice.

**Comment by Mlhozgr** [comment]
Hi Angie. I completed task , now i am writing about my report.Should i use English or can i use my native language?

**Comment by angievi** [comment]
> Hi Angie. I completed task , now i am writing about my report.Should i use English or can i use my native language?

What is your native language?

**Comment by Mlhozgr** [comment]
Turkish.If it is neccesary i can translate to English.

**Comment by angievi** [comment]
Turkish language will be a great addition!! please provide both turkish and english :)
Afterwards the team will review and I'll come back to you if the task fills the requirements so that you can proceed for the bounty. 
thanks!!

**Comment by Kolush1** [comment]
Hey there! Is there still space available to submit my task? I'm French so I'll write it in French but I can also translate in English if needed.

**Comment by angievi** [comment]
Hi @Kolush1 yes, you can still submit your report! english language will be perfect! 
Let us know when you have it ready, thanks for contributing to HDE!

**Comment by Kolush1** [comment]
Hi @angievi ! Here is my French report : https://drive.google.com/file/d/1y_zZ6ew-J8VOVDc9PPYd9gjoy1uuUfFQ/view.
I will translate it into English very soon, I will post the link as soon as it is done. Any comments please let me know :D

**Comment by Mlhozgr** [comment]
> @Mlhozgr Turkish language will be a great addition!! please provide both turkish and english :)
> Afterwards the team will review and I'll come back to you if the task fills the requirements so that you can proceed for the bounty.
> thanks!!

Hi Angie. Here is my report that is both Turkish and English. https://drive.google.com/file/d/1cL8Ev1pCiPT53Gnpi-rnhZcdrtbOUNdX/view?usp=sharing

**Comment by infinitEnigma** [comment]
Hey there, is this test still open? I would like to give it a try, wallet is currently syncing with blockchain.

**Comment by angievi** [comment]
> Hi @angievi ! Here is my French report : https://drive.google.com/file/d/1y_zZ6ew-J8VOVDc9PPYd9gjoy1uuUfFQ/view.
> I will translate it into English very soon, I will post the link as soon as it is done. Any comments please let me know :D

Hi @Kolush1 , can you please fill out the following form to claim the bounty: https://hde.horizen.io/landing-page/bounty-payout-policy , thank you!

**Comment by angievi** [comment]
> > > Hi @bricou26! Your submission is currently under review, I'll post here the following steps in case it complies with the requirements for the task.
> > > Thank you for contributing to HDE!
> > > Angie.
> > 
> > 
> > @bricou26 could you please follow the steps to fill the bounty form? : https://hde.horizen.io/landing-page/bounty-payout-policy
> > Any questions, let me know!
> > Angie.
> 
> The process have been completed :)
> 
> Do i need to close my pull request ?
> 
> Brice.

**Comment by angievi** [comment]
> Hey there, is this test still open? I would like to give it a try, wallet is currently syncing with blockchain.

Hello! @infinitEnigma yes, you can still participate on this HDE task! please provide your report with the instructions and format so we can review, thanks for contributing to HDE!

**Comment by angievi** [comment]
There are still 3 spots available for contributing to this HDE issue! 

Thank you all of those who have contributed already to HDE :)

**Comment by Mlhozgr** [comment]
> > @Mlhozgr Turkish language will be a great addition!! please provide both turkish and english :)
> > Afterwards the team will review and I'll come back to you if the task fills the requirements so that you can proceed for the bounty.
> > thanks!!
> 
> Hi Angie. Here is my report that is both Turkish and English. https://drive.google.com/file/d/1cL8Ev1pCiPT53Gnpi-rnhZcdrtbOUNdX/view?usp=sharing

Angie?

**Comment by Mlhozgr** [comment]
> > > @Mlhozgr Turkish language will be a great addition!! please provide both turkish and english :)
> > > Afterwards the team will review and I'll come back to you if the task fills the requirements so that you can proceed for the bounty.
> > > thanks!!
> > 
> > 
> > Hi Angie. Here is my report that is both Turkish and English. https://drive.google.com/file/d/1cL8Ev1pCiPT53Gnpi-rnhZcdrtbOUNdX/view?usp=sharing
> 
> Angie?

Are you still evaluating my report? Can you answer to me please?

**Comment by angievi** [comment]
> > > > @Mlhozgr Turkish language will be a great addition!! please provide both turkish and english :)
> > > > Afterwards the team will review and I'll come back to you if the task fills the requirements so that you can proceed for the bounty.
> > > > thanks!!
> > > 
> > > 
> > > Hi Angie. Here is my report that is both Turkish and English. https://drive.google.com/file/d/1cL8Ev1pCiPT53Gnpi-rnhZcdrtbOUNdX/view?usp=sharing
> > 
> > 
> > Angie?
> 
> Are you still evaluating my report? Can you answer to me please?

Hi! @Mlhozgr yes, your report is currently under evaluation, I'll get back to you as soon as it is completely reviewed :) thank you!

**Comment by infinitEnigma** [comment]
Hi @angievi, I've just finished testing and I'm preparing the report. Would you like a translation into Serbian as well?

**Comment by Kolush1** [comment]
> > Hi @angievi ! Here is my French report : https://drive.google.com/file/d/1y_zZ6ew-J8VOVDc9PPYd9gjoy1uuUfFQ/view.
> > I will translate it into English very soon, I will post the link as soon as it is done. Any comments please let me know :D
> 
> Hi @Kolush1 , can you please fill out the following form to claim the bounty: https://hde.horizen.io/landing-page/bounty-payout-policy , thank you!

Hi @angievi ! The form is filled and here is my Engligh report : https://drive.google.com/file/d/12dLMmN4o7Tareu-KCl-PUqT1hi7i0Pa3

Have a nice end of the year!

**Comment by infinitEnigma** [comment]
@angievi here is my English test report:
https://github.com/infinitEnigma/HorizenSideChains_test

**Comment by angievi** [comment]
> Hi @angievi, I've just finished testing and I'm preparing the report. Would you like a translation into Serbian as well?

Hello @infinitEnigma , your report is under evaluation and please also provide it in Serbian, it will be very useful for the community! thank you

**Comment by angievi** [comment]
> > > @Mlhozgr Turkish language will be a great addition!! please provide both turkish and english :)
> > > Afterwards the team will review and I'll come back to you if the task fills the requirements so that you can proceed for the bounty.
> > > thanks!!
> > 
> > 
> > Hi Angie. Here is my report that is both Turkish and English. https://drive.google.com/file/d/1cL8Ev1pCiPT53Gnpi-rnhZcdrtbOUNdX/view?usp=sharing
> 
> Angie?

Hi! @Mlhozgr can you please fill out the following form to claim the bounty: https://hde.horizen.io/landing-page/bounty-payout-policy , thank you!

**Comment by infinitEnigma** [comment]
> > Hi @angievi, I've just finished testing and I'm preparing the report. Would you like a translation into Serbian as well?
> 
> Hello @infinitEnigma , your report is under evaluation and please also provide it in Serbian, it will be very useful for the community! thank you

Hello @angievi, here's a link to the Serbian translation:
https://github.com/infinitEnigma/HorizenSideChains_test/blob/main/SideChainTest_SerbianTranslation.md
😃

**Comment by downsun** [comment]
> > https://drive.google.com/file/d/12xfnQ5Cfwhe4-f6YX_q68VeFMxln50N0/view?ths=true
> 
> Hi @downsun , could you please follow the steps here to claim your bounty? https://hde.horizen.io/landing-page/bounty-payout-policy , any questions please let me know! thanks :)

I submitted a request，thanks

**Comment by angievi** [comment]
> @angievi here is my English test report:
> https://github.com/infinitEnigma/HorizenSideChains_test

Hi @infinitEnigma , please also translate to serbian! :) your contribution is under review atm! thanks!!

**Comment by infinitEnigma** [comment]
> > @angievi here is my English test report:
> > https://github.com/infinitEnigma/HorizenSideChains_test
> 
> Hi @infinitEnigma , please also translate to serbian! :) your contribution is under review atm! thanks!!
Hi @angievi,  here's a link to the Serbian translation:
https://github.com/infinitEnigma/HorizenSideChains_test/blob/main/SideChainTest_SerbianTranslation.md
and English version: https://github.com/infinitEnigma/HorizenSideChains_test/blob/main/README.md

**Comment by downsun** [comment]
> > > https://drive.google.com/file/d/12xfnQ5Cfwhe4-f6YX_q68VeFMxln50N0/view?ths=true
> > 
> > 
> > 嗨@downsun，您能按照这里的步骤申请赏金吗？https://hde.horizen.io/landing-page/bounty-payout-policy，如有任何问题，请告诉我！谢谢 ：）
> 
> 我提交了一个请求，谢谢

This is the Chinese version I submitted:

https://github.com/downsun/Horizen-/blob/main/README.md

I added LICENSE.

Where did you submit the Zen address？

What else do you need?

**Comment by Mlhozgr** [comment]
Hello Angie. I performed the necessary steps 7 days ago. When can I get the bounty?

**Comment by angievi** [comment]
> Hello Angie. I performed the necessary steps 7 days ago. When can I get the bounty?

Please wait while we finish to review and the request for payment will be sent shortly, thanks!

**Comment by angievi** [comment]
Hi, can you please submit your request again:  https://hde.horizen.io/landing-page/bounty-payout-policy and also add your information and send it here: angie@horizen.io please? thanks!

**Comment by francov99** [comment]
Hello everyone, here I share my first report for horizen https://docs.google.com/document/d/1GDporsABahLHUP_eVIR8UPM9LjnLUXo7uAahz4Fjvrs/edit?usp=sharing

**Comment by angievi** [comment]
> Hello everyone, here I share my first report for horizen https://docs.google.com/document/d/1GDporsABahLHUP_eVIR8UPM9LjnLUXo7uAahz4Fjvrs/edit?usp=sharing

Hi @francov99 your report is being reviewed, I'll come back to you if it complies with the requirements and the process to follow to apply for the bounty! thanks!

**Comment by infinitEnigma** [comment]
Hi @angievi, what is the status of my report? Should I fill the bounty form?

**Comment by Kolush1** [comment]
Hi @angievi / others, could you please give us some updates on the advancement of the reviews / bounties ?

**Comment by angievi** [comment]
Hi @Kolush1 @Mlhozgr @downsun your contributions have been reviewed and approved. Your bounties should arrive soon. Thanks for contributing to HDE!

**Comment by angievi** [comment]
> Hi @angievi, what is the status of my report? Should I fill the bounty form?

Hi @infinitEnigma , yes, can you please fill the form: https://hde.horizen.io/landing-page/bounty-payout-policy , thank you!

**Comment by angievi** [comment]
There are only 2 spots left for contributing to this HDE issue!

**Comment by infinitEnigma** [comment]
> > Hi @angievi, what is the status of my report? Should I fill the bounty form?
> 
> Hi @infinitEnigma , yes, can you please fill the form: https://hde.horizen.io/landing-page/bounty-payout-policy , thank you!

@angievi, done, thank you!

**Comment by rickmort** [comment]
@angievi  Can I still submit my report?

**Comment by rickmort** [comment]
I could not stay with the desire to try it. 

I am eager to try some extra features. @angievi 

https://docs.google.com/document/d/19LWxyTkTrQ_e9VG4cofMSSgoKUES152A1jlzaxT1DMI/edit?usp=sharing

**Comment by neiithanlv** [comment]
I want to participate in this task

**Comment by angievi** [comment]
ok thanks for your contribution @rickmort , it is currently under review. Will come back to you with an answer soon.

**Comment by angievi** [comment]
> I want to participate in this task

Ok, @neiithanlv Please provide a report with the requirements to complete the task.

**Comment by angievi** [comment]
> > Hello everyone, here I share my first report for horizen https://docs.google.com/document/d/1GDporsABahLHUP_eVIR8UPM9LjnLUXo7uAahz4Fjvrs/edit?usp=sharing
> 
> Hi @francov99 your report is being reviewed, I'll come back to you if it complies with the requirements and the process to follow to apply for the bounty! thanks!

Hi @francov99 can you please fill your information here to claim your bounty: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!

**Comment by Maharadga** [comment]
Good day. Need a hint. When I run Sphere_by_Horizen_Sidechain_Testnet I get an inscription "You have another instance of zend running. Please terminate it and click on retry" How to deal with this problem?

**Comment by infinitEnigma** [comment]
> Good day. Need a hint. When I run Sphere_by_Horizen_Sidechain_Testnet I get an inscription "You have another instance of zend running. Please terminate it and click on retry" How to deal with this problem?

try `pkill -9 zend ` command if on Linux or `task manager (/details tab, stop process)` on Windows

**Comment by Andreas2000** [comment]
Hi @angievi 
I have finished with the particular task and I am ready to write my report.
For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?

**Comment by Andreas2000** [comment]
@angievi 
My report in PDF format
https://drive.google.com/file/d/1p6S2U2VB_c-U6pPjWcRJJvLPS0FkExv1/view?usp=sharing

**Comment by Kolush1** [comment]
> Hi @Kolush1 @Mlhozgr @downsun your contributions have been reviewed and approved. Your bounties should arrive soon. Thanks for contributing to HDE!

Hi @angievi ! Sorry to disturb but I haven't received my bounty yet and I'm not 100% sure I did all the steps required. 

I don't want to create a duplicate on the website hde.horizen.io so please when you have some time, could you check if it's ok for me please ? If it is, I'll just wait, no problem !

**Comment by infinitEnigma** [comment]
Hi @angievi I didn't receive my bounties, is there anything more I have to do? 
Thank you

**Comment by mzaghab** [comment]
Hi @angievi is this task still open ?

**Comment by angievi** [comment]
> Hi @angievi
> I have finished with the particular task and I am ready to write my report.
> For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?

Yes, please provide it in greek as well as in english! thanks for contributing

**Comment by angievi** [comment]
> Hi @angievi I didn't receive my bounties, is there anything more I have to do?
> Thank you

Hi @infinitEnigma, The request for payment is in progress, thanks!!

**Comment by angievi** [comment]
> Hi @angievi is this task still open ?

Hey @mzaghab this task has already reached the number of contributions allowed. You can still create a sidechain here: https://github.com/HorizenOfficial/Sidechains-SDK/issues/151

**Comment by Andreas2000** [comment]
> > Hi @angievi
> > I have finished with the particular task and I am ready to write my report.
> > For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?
> 
> Yes, please provide it in greek as well as in english! thanks for contributing

Hi again @angievi 
Here is the report in English
https://drive.google.com/file/d/1p6S2U2VB_c-U6pPjWcRJJvLPS0FkExv1/view?usp=sharing

**Comment by virgodarth** [comment]
Hi there,
Can I know when this task close?

**Comment by angievi** [comment]
> https://docs.google.com/document/d/19LWxyTkTrQ_e9VG4cofMSSgoKUES152A1jlzaxT1DMI/edit?usp=sharing

Hi @rickmort , can you please fill the information in this form: https://hde.horizen.io/landing-page/bounty-payout-policy , thanks!

**Comment by angievi** [comment]
> > > Hi @angievi
> > > I have finished with the particular task and I am ready to write my report.
> > > For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?
> > 
> > 
> > Yes, please provide it in greek as well as in english! thanks for contributing
> 
> Hi again @angievi
> Here is my report in English
> https://drive.google.com/file/d/1p6S2U2VB_c-U6pPjWcRJJvLPS0FkExv1/view?usp=sharing

Hi @Andreas2000 can you please fill this form: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!

**Comment by Maharadga** [comment]
Hi Angie. I completed task. I should write the report in English or can i use my native language? I from Russia

**Comment by Andreas2000** [comment]
> > > > Hi @angievi
> > > > I have finished with the particular task and I am ready to write my report.
> > > > For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?
> > > 
> > > 
> > > Yes, please provide it in greek as well as in english! thanks for contributing
> > 
> > 
> > Hi again @angievi
> > Here is my report in English
> > https://drive.google.com/file/d/1p6S2U2VB_c-U6pPjWcRJJvLPS0FkExv1/view?usp=sharing
> 
> Hi @Andreas2000 can you please fill this form: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!

Also thanking you @angievi!
I have send the form as requested

I have a question for you
Can I publish my report to medium.com and/or to bitcointalk.org?

**Comment by Hopeesams** [comment]
Can I still work on this?

**Comment by angievi** [comment]
> > > > > Hi @angievi
> > > > > I have finished with the particular task and I am ready to write my report.
> > > > > For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?
> > > > 
> > > > 
> > > > Yes, please provide it in greek as well as in english! thanks for contributing
> > > 
> > > 
> > > Hi again @angievi
> > > Here is my report in English
> > > https://drive.google.com/file/d/1p6S2U2VB_c-U6pPjWcRJJvLPS0FkExv1/view?usp=sharing
> > 
> > 
> > Hi @Andreas2000 can you please fill this form: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!
> 
> Also thanking you @angievi!
> I have send the form and claimed the bounty as requested
> 
> I have a question for you
> Can I publish my report to medium.com and/or to bitcointalk.org?

Sure! please feel free to publish your report on other websites :) it helps the community to get more involved with the Horizen ecosystem!

**Comment by infinitEnigma** [comment]
> > Hi @angievi I didn't receive my bounties, is there anything more I have to do?
> > Thank you
> 
> Hi @infinitEnigma, The request for payment is in progress, thanks!!

Hi @angievi, any news regarding the bounties? thanks

**Comment by Maharadga** [comment]
Here is my report in English ://docs.google.com/document/d/1AsBAAzd8OWlXhGhLjnGlcDfGZD1bnWn1ZioPWeCSsgA/edit?usp=sharing

**Comment by Sanjorge1** [comment]
Hola! 
La tarea está aún disponible?
Podría realizarla a través de un móvil?

Gracias.

**Comment by lechris1988** [comment]
bonjours, toujours disponible ? merci

**Comment by lechris1988** [comment]
> Hi !
> 
> I wrote a report about this task, here's the link : https://cryptochu.fr/comment-lancer-une-sidechain-horizen-a-partir-du-wallet-sphere-by-horizen/
> For now, it's a French report but I can translate it if necessary.

bonjours, je vois que tu es francais aussi, aurais tu quelque minutes pour moi ? merciii

**Comment by tabullarasa** [comment]
Hi zen ❤️ isthis still available? I speak 5 languages ,should i do it in all

**Comment by angievi** [comment]
> https://docs.google.com/document/d/1AsBAAzd8OWlXhGhLjnGlcDfGZD1bnWn1ZioPWeCSsgA/edit?usp=sharing

Hi @Maharadga , yes please fill your information here: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!

**Comment by angievi** [comment]
@Sanjorge1 @lechris1988 @tabullarasa this HDE task has reached the number of participants allowed already. I invite you to check out our other open HDE issues and upcoming ones that will be added soon! 

Thanks for your interest in HDE!

Angie.

**Comment by angievi** [comment]
> > > > > > Hi @angievi
> > > > > > I have finished with the particular task and I am ready to write my report.
> > > > > > For sure I will write it in Greek and post it in Medium, shall I also write it in English as well?
> > > > > 
> > > > > 
> > > > > Yes, please provide it in greek as well as in english! thanks for contributing
> > > > 
> > > > 
> > > > Hi again @angievi
> > > > Here is my report in English
> > > > https://drive.google.com/file/d/1p6S2U2VB_c-U6pPjWcRJJvLPS0FkExv1/view?usp=sharing
> > > 
> > > 
> > > Hi @Andreas2000 can you please fill this form: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!
> > 
> > 
> > Also thanking you @angievi!
> > I have send the form and claimed the bounty as requested
> > I have a question for you
> > Can I publish my report to medium.com and/or to bitcointalk.org?
> 
> Sure! please feel free to publish your report on other websites :) it helps the community to get more involved with the Horizen ecosystem!

Hi, @Andreas2000 can you please fill out the form for payment : https://hde.horizen.io/landing-page/bounty-payout-policy thanks!

**Comment by lechris1988** [comment]
ha, j ai fini, j allai l envoyer...

**Comment by Maharadga** [comment]
> > https://docs.google.com/document/d/1AsBAAzd8OWlXhGhLjnGlcDfGZD1bnWn1ZioPWeCSsgA/edit?usp=sharing
> 
> Hi @Maharadga , yes please fill your information here: https://hde.horizen.io/landing-page/bounty-payout-policy thanks!

Please tell me how to properly get rewarded for bounty step by step. https://hde.horizen.io/landing-page/bounty-payout-policy this link is all in English. And the online translator is not very good at translating and many things are not clear. And I can't quite figure out what I should do. Maybe someone can explain it to me in more detail. I'd appreciate it.

**Comment by Maharadga** [comment]
Good afternoon. Can you tell me if there is still a reward for this task? Or not anymore?

**Comment by angievi** [comment]
> Good afternoon. Can you tell me if there is still a reward for this task? Or not anymore?

Hi @Maharadga , this issue has reached the limit of participants already, we invite you to check out more upcoming HDE activities, thanks!
