### ISSUE TITLE
Javascript error ENAMETOOLONG awd file backup

### ISSUE THREAD

**Issue by gernoox** [HorizenOfficial/Sphere_by_Horizen#42]
OS: Ubuntu 20.04LTS / Kernel 5.4 
Sphere Version: 1.2.8-Beta
Once zend is synced, I get that recursive error that makes Sphere unusable.

![Capture_sphere](https://user-images.githubusercontent.com/23701805/101125680-19731280-35fa-11eb-9620-3950dd49b678.JPG)

**Comment by cronicc** [comment]
@gernoox Is your /home filesystem FAT32 by any chance?
https://stackoverflow.com/questions/54741533/nodejs-enametoolong-how-long-is-too-long

**Comment by gernoox** [comment]
> @gernoox Is your /home filesystem FAT32 by any chance?
> https://stackoverflow.com/questions/54741533/nodejs-enametoolong-how-long-is-too-long

@cronicc no no !! My filesystem is Ext4, in doubt: I "force fsck"-ed it without error. 
I use Sphere since almost 2y, every updates took place without issue.
Since halving, I get that error, strange isn't it !?
Ps: I have several backups and snapshots (I use vSphere VM system) so I'm absolutely not worried :-) 
I will start a copy backup and see if ENAMETOOLONG error will come back.

**Comment by gernoox** [comment]
Update
I started an old VM backup(sept-20) with Sphere v1.2.7 / Ubuntu 18.04.
I updated Sphere to 1.2.8 ; Zend updated too. 
Sync began: no problem, several hours later: ONLY WHEN Zend is fully synced : the ERROR appears and Sphere becomes unusable.
There is a way to change the name of that f*cking awd file in the Sphere conf somewhere ?

**Comment by gernoox** [comment]
Update
Just create a new account for test: same error.

![Capture_sphere2](https://user-images.githubusercontent.com/23701805/101691180-9aa12e00-3a6e-11eb-8e68-8df346561b9f.JPG)

**Comment by paolocappelletti** [comment]
hi @gernoox , that file is the wallet file, cannot be renamed. there is a new feature on the latest Sphere that automatically makes a  backup copy of the file on every change, and that operation seems to fail on your installation. 
Can you check if you have set an encrypted filesystem for your home folder? I found a similar issue from a user having eCryptFS  enabled  - https://github.com/npm/npm/issues/2598
If so, to check if is  really that the problem and as a temporary solution, you could try to symlink the backups/ folder to another location outside the homedir

**Comment by gernoox** [comment]
Hi @paolocappelletti 
YeeeeeeeeeeS. F*ck !! You're right :-)
Indeed my /home is encrypted; So follow your advice: I symlinked the 'wallets' folder outside the encrypted zone...
and it's confirmed -> Sphere is running fine.
Thank you very very very much **Sir**.
Ed_
