### ISSUE TITLE
Any withdraw password works

### ISSUE THREAD

**Issue by tonyimoon** [HorizenOfficial/Sphere_by_Horizen#53]
There is a bug on Horizen Sphere.
I am using version 1.2.8-beta
You can use any Password to withdraw funds

**Comment by SpencerWhetstone-Horizen** [comment]
I can confirm that this occurs when performing a batch withdrawal . I am using 1.2.8-beta on Mac Mini.
The wallet spend password is not enforced on a batch withdrawal.

Model Name:	Mac mini
  Model Identifier:	Macmini9,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	6723.81.1
  Serial Number (system):	H2WF70TZQ6P0
  Hardware UUID:	34EBEE61-EA66-5369-9370-1D48952DA414
  Provisioning UDID:	00008103-00060C590AEA001E
  Activation Lock Status:	Enabled

**Comment by rosariopabst** [comment]
> There is a bug on Horizen Sphere.
> I am using version 1.2.8-beta
> You can use any Password to withdraw funds

Thank you for reporting. We are investigating and update you soon.

**Comment by rosariopabst** [comment]
We fixed the issue and the fix will be available in the next Sphere release. The wallet is protected with the main password. this is  the second (optional) password used to confirm the batch withdraw. Thank you for reporting!

**Comment by cronicc** [comment]
Fixed in https://github.com/HorizenOfficial/Sphere_by_Horizen/releases/tag/desktop-v1.2.10-beta
