### ISSUE TITLE
"Oops, wrong wallet password. Please try it again" when trying to create a new address 

### ISSUE THREAD

**Issue by kiwibayer** [HorizenOfficial/Sphere_by_Horizen#83]
As the title says. 
I'm getting the following message when trying to create a new address in my wallet

"Oops, wrong wallet password. Please try it again"

same when trying to create a private address
chain is 100% synced 
Full mode
1.5.0-beta

**Comment by jurgis** [comment]
@kiwibayer I have the same error in light mode when using AppImage 1.5.0 on Ubuntu Linux.
When using the previous version 1.4.0, it is working without the error.

**Comment by kiwibayer** [comment]
tried to create the same wallet within the same account inside Sphere and that somehow seems to have "fixed" it. 

I got an error saying the wallet with the seed already exists, and afterwards I was able to create a new address. 
Must have been something todo with upgrading the sphere version.
